[package]
name = "dar2oar_core"
version = "0.1.0"
description = "DAR to OAR Converter Core"
authors = ["SARDONYX-sard"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/SARDONYX-sard/dar2oar"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
log = "0.4.20"                                            # Logger
nom = { version = "7.1.3", features = ["alloc"] }         # Syntax
serde = { version = "1.0", features = ["derive"] }        # Implement (De)Serializer
serde_json = "1.0"                                        # Json converter
thiserror = "1.0.48"                                      # define errors type
walkdir = "2.4.0"                                         # To traverse dir recursivly

[dev-dependencies]
pretty_assertions = "1.4.0"
simple-log = "1.6.0"
