name: Build & Test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_NAME: g_dar2oar
  BUILD_PROFILE: release-no-lto
  CARGO_TERM_COLOR: always

jobs:
  lint:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: true
      - name: Setup environment
        uses: ./.github/actions/setup-deps
        with:
          platform: ${{ matrix.platform }}
          build_profile: debug
          install_front_deps: false

      - name: Check format
        run: rustup component add rustfmt;cargo fmt --all -- --check

      - name: Install Python 3.14(To avoid lint error)
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Lint Check
        run: rustup component add clippy;cargo clippy --workspace -- -D warnings

  test:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: true
      - name: Setup environment
        uses: ./.github/actions/setup-deps
        with:
          platform: ${{ matrix.platform }}
          build_profile: debug
          install_front_deps: false

      - name: Install nextest(Parallel Test Execution CLI)
        uses: taiki-e/install-action@nextest

      - name: Test(Rust)
        run: cargo nextest run --workspace --no-fail-fast

  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: true
      - name: Setup environment
        uses: ./.github/actions/setup-deps
        with:
          platform: ${{ matrix.platform }}
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Test(Node.js)
        run: npm test
      - name: Build GUI
        run: npm run build

      - name: Move exe -> ./build
        uses: ./.github/actions/setup-release
        with:
          app_name: ${{ env.APP_NAME }}
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ${{ env.APP_NAME }}-${{ runner.os }}
          # to include .keep file
          include-hidden-files: true
          path: |
            ./build/

  cli:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: true
      - name: Setup environment
        uses: ./.github/actions/setup-deps
        with:
          platform: ${{ matrix.platform }}
          build_profile: release
          cache_key_suffix: "cli"
          install_front_deps: false

      - name: Build GUI
        run: cargo build -p dar2oar --profile ${{ env.BUILD_PROFILE }}
      - name: Move exe -> ./build
        uses: ./.github/actions/setup-release
        with:
          app_name: dar2oar
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ${{ env.APP_NAME }}-${{ runner.os }}-cli
          include-hidden-files: true # to include .keep file
          path: |
            ./build/
