name: Cargo Lint & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - uses: actions/checkout@v3

      - name: Run lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace
        if: matrix.platform == 'ubuntu-20.04'

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
