name: Release GUI
on:
  push:
    tags:
      - "*"

env:
  APP_NAME: dar2oar
  BUILD_PROFILE: release

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup environment
        uses: ./.github/actions/setup-deps
        with:
          platform: ${{ matrix.platform }}
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Update CHANGELOG
        if: runner.os == 'Windows'
        id: changelog
        uses: requarks/changelog-action@v1.10.3
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Build GUI
        run: npm run build:release

      - name: Move exe -> ./build
        uses: ./.github/actions/setup-release
        with:
          app_name: ${{ env.APP_NAME }}
          build_profile: ${{ env.BUILD_PROFILE }}

      - name: Compress outputs(Windows)
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path './build/*' -DestinationPath './${{ env.APP_NAME }}_tauri-${{ runner.os }}-v${{ github.ref_name }}.zip'

      - name: Release Portable Version(Windows)
        uses: ncipollo/release-action@v1.21.0
        if: runner.os == 'Windows'
        with:
          allowUpdates: true
          artifacts: ./*.zip
          name: "${{ env.APP_NAME }} v${{ github.ref_name }}"
          body: ${{ steps.changelog.outputs.changes }}
          tag: ${{ github.ref_name }}

      - name: Commit CHANGELOG.md
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout main
          git pull origin main

          # Stage only CHANGELOG.md
          git add CHANGELOG.md

          # Drop Others.
          git restore .
          git clean -fd

          git commit -m "docs: update CHANGELOG.md for ${{ github.ref_name }}" `
            || echo "No changes to commit"

          git push origin main

      - name: Compress outputs(MacOS/Linux)
        shell: bash
        if: runner.os != 'Windows'
        run: |
          tar -czf ./${{ env.APP_NAME }}_tauri-${{ runner.os }}-v${{ github.ref_name }}.tar.gz -C ./build .

      - name: Release Portable Version
        uses: ncipollo/release-action@v1.21.0
        if: runner.os != 'Windows'
        with:
          allowUpdates: true
          artifacts: ./*.tar.gz
          name: "${{ env.APP_NAME }} v${{ github.ref_name }}"
          tag: ${{ github.ref_name }}
