name: Release GUI
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.5
        with:
          prefix-key: cargo-${{ matrix.platform }}

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Node.js cache
        uses: actions/cache@v4.1.2
        with:
          path: ${{ github.workspace }}/gui/frontend/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('gui/frontend/src/**/*.[jt]s', 'gui/frontend/src/**/*.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install frontend dependencies
        run: npm ci

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
        if: runner.os == 'macOS'

      - name: Build the app
        uses: tauri-apps/tauri-action@action-v0.5.15

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: 'DAR to OAR Converter v__VERSION__'
          tagName: ${{ github.ref_name }}
          releaseBody: ${{ steps.changelog.outputs.changes }}
          prerelease: false

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
        if: runner.os == 'macOS'
